/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
export default {
  community: [
    // {
    //   type: 'autogenerated',
    //   dirName: '.',
    // },
    { type: 'doc', id: 'support' },
    { type: 'doc', id: 'team' },
    // { type: 'doc', id: 'resources' },
    // { type: 'doc', id: 'contributing' },
    // {
    //   type: 'link',
    //   href: '/changelog',
    //   label: 'Changelog',
    // },
    // {
    //   type: 'link',
    //   href: '/feature-requests',
    //   label: 'Feature Requests',
    // },
    {
      type: 'link',
      label: 'Chat with us on Slack',
      href: 'http://t.uber.com/cadence-slack',
    },
  ],
};
