{
 "title": "Cadence Server",
 "description": "An initial dashboard for prometheus metrics from https://github.com/uber/cadence",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(cadence_requests,namespace)"
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": "label_values(activity_end_to_end_latency_sum{namespace=\"$namespace\"}, domain)"
   },
   { "name": "quantiles", "label": "Quantiles", "query": "0.5, 0.95, 0.99" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Vs Error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_errors{namespace=\"$namespace\"}[2m])",
     "legendFormat": "Errors - {{ instance }}:{{ operation }}:",
     "target": "fetch service:cadence-frontend deployment:$deployment name:{cadence_errors,cadence_requests} | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
    },
    {
     "expr": "rate(cadence_requests{namespace=\"$namespace\"}[2m])",
     "legendFormat": "Requests - {{ instance }}:{{ operation }}:{{ domain }}"
    }
   ]
  },
  {
   "title": "Error Breakdown",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cadence_errors_bad_request{namespace=\"$namespace\"}[2m])",
     "legendFormat": "bad_requests -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_bad_request | transformNull 0 | sum | scaleToSeconds 1 | alias BadRequest"
    },
    {
     "expr": "rate(cadence_errors_service_busy{namespace=\"$namespace\"}[2m])",
     "legendFormat": "service_busy -  {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_service_busy | transformNull 0 | sum | scaleToSeconds 1 | alias ServiceBusy"
    },
    {
     "expr": "rate(cadence_errors_entity_not_exists{namespace=\"$namespace\"}[2m])",
     "legendFormat": "entity_not_exists -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_entity_not_exists | transformNull 0 | sum | scaleToSeconds 1 | alias EntityNotExist"
    },
    {
     "expr": "rate(cadence_errors_execution_already_started{namespace=\"$namespace\"}[2m])",
     "legendFormat": "execution_already_started  -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_execution_already_started | transformNull 0 | sum | scaleToSeconds 1 | alias ExecutionAlreadyStarted"
    },
    {
     "expr": "rate(cadence_errors_domain_already_exists{namespace=\"$namespace\"}[2m])",
     "legendFormat": "domain_already_exists  -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_domain_already_exists | transformNull 0 | sum | scaleToSeconds 1 | alias DomainAlreadyExists"
    },
    {
     "expr": "rate(cadence_errors_cancellation_already_requested{namespace=\"$namespace\"}[2m])",
     "legendFormat": "cancellation_already_requested  -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_cancellation_already_requested | transformNull 0 | sum | scaleToSeconds 1 | alias CancellationAlreadyRequested"
    },
    {
     "expr": "rate(cadence_errors_context_timeout{namespace=\"$namespace\"}[2m])",
     "legendFormat": "errors_context_timeout  -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_context_timeout | transformNull 0 | sum | scaleToSeconds 1 | alias ContextTimeout"
    },
    {
     "expr": "rate(cadence_errors_limit_exceeded{namespace=\"$namespace\"}[2m])",
     "legendFormat": "limit_exceeded  -   {{ instance }}:{{ operation }} : {{ domain }}",
     "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_errors_limit_exceeded | transformNull 0 | sum | scaleToSeconds 1 | alias LimitExceeded"
    },
    {
     "expr": "rate(cadence_errors_query_failed{namespace=\"$namespace\"}[2m])",
     "legendFormat": "query_failed -   {{ instance }}:{{ operation }} : {{ domain }}"
    },
    {
     "expr": "rate(cadence_errors_shard_ownership_lost{namespace=\"$namespace\"}[2m])",
     "legendFormat": "shard_ownership_lost -   {{ instance }}:{{ operation }} : {{ domain }}"
    },
    { "expr": "erro" }
   ]
  },
  {
   "title": "Cache requests vs miss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_miss{namespace=\"$namespace\"}[2m])) by (cache_type, operation)",
     "legendFormat": "miss-{{ cache_type}}-{{ operation }}"
    },
    {
     "expr": "sum(rate(cache_requests{namespace=\"$namespace\"}[2m])) by (cache_type, operation)",
     "legendFormat": "requests-{{ cache_type}}-{{ operation }}"
    }
   ]
  },
  {
   "title": "Cache errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cache_errors{namespace=\"$namespace\"}[2m])) by (cache_type, operation)",
     "legendFormat": "{{ cache_type}}-{{ operation }}"
    }
   ]
  },
  {
   "title": "Cache latencies p99",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, sum(rate(cache_latency_bucket{namespace=\"$namespace\"}[2m])) by (le, cache_type, operation))",
     "legendFormat": "{{ cache_type}}-{{ operation }}"
    }
   ]
  },
  {
   "title": "Frontend API Latencies",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\"}[2m]))))",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Frontend Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Frontend Client Request Vs Error",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cadence_client_errors{namespace=\"$namespace\"}[2m])",
       "legendFormat": "errors -  {{ instance }}:{{ operation }} : {{ domain }}",
       "target": "fetch service:cadence-frontend deployment:$deployment name:{cadence_client_errors,cadence_client_requests} | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
      },
      {
       "expr": "rate(cadence_client_requests{namespace=\"$namespace\"}[2m])",
       "legendFormat": "requests -   {{ instance }}:{{ operation }} : {{ domain }}"
      }
     ]
    },
    {
     "title": "Frontend Client API Latencies",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_client_latency_bucket{namespace=\"$namespace\"}[2m]))))",
       "legendFormat": "{{ operation }}",
       "target": "fetch service:cadence-frontend deployment:$deployment  name:cadence_client_latency timertype:$latency  | transformNull 0 | aliasByTags operation"
      }
     ]
    }
   ]
  },
  {
   "title": "API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "StartWorfklowExecution",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cadence_requests{operation=\"StartWorkflowExecution\", namespace=\"$namespace\"}[2m])",
       "legendFormat": "requests -  {{ instance }}:{{ operation }} : {{ domain }}",
       "target": "fetch service:$service deployment:$deployment name:cadence_{errors_*,requests} operation:startworkflowexecution | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
      },
      {
       "expr": " rate(cadence_errors{operation=\"StartWorkflowExecution\", namespace=\"$namespace\"}[2m])",
       "legendFormat": "errors -  {{ instance }}:{{ operation }} : {{ domain }}"
      }
     ]
    },
    {
     "title": "Operation Latencies",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(cadence_latency_bucket{namespace=\"$namespace\"}[2m])) by (le, operation))",
       "legendFormat": "{{ operation }}",
       "target": "fetch service:$service deployment:$deployment timertype:{lower,median,p99,upper} operation:startworkflowexecution | transformNull 0 |  summarize 1min avg | avg timertype | aliasByTags timertype"
      }
     ]
    },
    {
     "title": "PollForActivityTask",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cadence_requests{operation=\"PollForActivityTask\", namespace=\"$namespace\"}[2m])",
       "legendFormat": "requests -  {{ instance }}:{{ operation }} : {{ domain }}",
       "target": "fetch service:$service deployment:$deployment name:cadence_{errors_*,requests} operation:pollforactivitytask | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
      },
      {
       "expr": "rate(cadence_errors{operation=\"PollForActivityTask\", namespace=\"$namespace\"}[2m])",
       "legendFormat": "errors -  {{ instance }}:{{ operation }} : {{ domain }}",
       "target": "fetch service:cadence-frontend deployment:$deployment name:cadence_requests operation:pollforactivitytask | sum | summarize 1m sum | diff (fetch service:cadence-frontend deployment:$deployment operation:pollforactivitytask name:cadence_errors | sum | summarize 1m sum) | asPercent (fetch service:cadence-frontend deployment:$deployment name:cadence_requests operation:pollforactivitytask | sum | summarize 1m sum) | transformNull 100 | alias availability"
      }
     ]
    }
   ]
  },
  {
   "title": "Persistence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Vs Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(persistence_errors{namespace=\"$namespace\"}[2m])",
       "legendFormat": "Errors - {{ instance }}:{{ operation }}:",
       "target": "fetch service:cadence-frontend deployment:$deployment name:persistence_{errors,requests}  | transformNull 0 | sum name | scaleToSeconds 1 | aliasByTags name"
      },
      {
       "expr": "rate(persistence_requests{namespace=\"$namespace\"}[2m])",
       "legendFormat": "Requests - {{ instance }}:{{ operation }}:"
      }
     ]
    },
    {
     "title": "Operation Latencies p99",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(persistence_latency_bucket{namespace=\"$namespace\"}[2m])) by (le, operation))",
       "legendFormat": "{{ operation }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Shard acquisition latency p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(acquire_shards_latency_bucket{namespace=\"$namespace\"}[2m])) by (le, operation, type))",
       "legendFormat": "shard_acquisition_latency-{{ operation }}-{{ type }}"
      },
      {}
     ]
    },
    {
     "title": "Shardinfo replication lag p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(shardinfo_replication_lag_bucket{namespace=\"$namespace\"}[2m])) by (le, operation, type))",
       "legendFormat": "shardinfo_replication_lag-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo timer failover in progress",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(shardinfo_timer_failover_in_progress_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "shardinfo_timer_failover_in_progress_count-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo timer active pending task",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(shardinfo_timer_active_pending_task_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "shardinfo_timer_active_pending_task-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo timer lag bucket p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(shardinfo_timer_lag_bucket{namespace=\"$namespace\"}[2m])) by (le, operation, type))",
       "legendFormat": "shardinfo_timer_lag-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo timer diff",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(shardinfo_timer_diff_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "shardinfo_timer_diff_count-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo transfer lag p99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(shardinfo_transfer_lag_bucket{namespace=\"$namespace\"}[2m])) by (le, operation, type))",
       "legendFormat": "shardinfo_transfer_lag-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo transfer active pending task",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(shardinfo_transfer_active_pending_task_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "shardinfo_transfer_active_pending_task_count-{{ operation }}-{{ type }}"
      }
     ]
    },
    {
     "title": "Shardinfo transfer failover in progress",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(shardinfo_transfer_failover_in_progress_count{namespace=\"$namespace\"}[2m])",
       "legendFormat": "shardinfo_transfer_failover_in_progress_count-{{ operation }}-{{ type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Metrics by SQUAD: NAME_OF_SQUAD",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Workflows Success by type (absolute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "\r\nsum (workflow_success{namespace=\"$namespace\"})  by (tasklist, domain) "
    }
   ]
  },
  {
   "title": "Workflows Failed by type (absolute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (workflow_failed\r{namespace=\"$namespace\"}) \rby (tasklist, domain)  ",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Workflows Canceled by type (absolute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (workflow_cancel{namespace=\"$namespace\"}) \rby (tasklist, domain)  ",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Workflows Timeout by type (absolute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (workflow_timeout{namespace=\"$namespace\"}) \rby (tasklist, domain)  ",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Workflows Success by type (Relative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workflow_success {domain=\"$domain\",namespace=\"$namespace\"}[1m])",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Workflows Failed by type (Relative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workflow_failed {domain=\"$domain\",namespace=\"$namespace\"} [5m])",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Workflows Canceled by type (Relative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workflow_cancel{domain=\"$domain\",namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Workflows TimeOut by type (Relative)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(workflow_timeout{domain=\"$domain\",namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{ tasklist }}"
    }
   ]
  },
  {
   "title": "Activities latency (rate by count & sum by activity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " rate( activity_end_to_end_latency_sum {domain=\"$domain\",namespace=\"$namespace\"}[2m]) /rate(activity_end_to_end_latency_count{domain = \"$domain\",namespace=\"$namespace\"}[2m])\r ",
     "legendFormat": "{{ activityType }}:{{ workflowType }}"
    }
   ]
  },
  {
   "title": "Activities latency (absolute sum by activity)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "  sum  (activity_end_to_end_latency_bucket{domain=\"$domain\",namespace=\"$namespace\"})  \rby (activityType)  "
    }
   ]
  },
  {
   "title": "Activities latency - global peak detection",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(activity_end_to_end_latency_bucket {domain=\"$domain\",namespace=\"$namespace\"}  [5m])) by (le) )"
    }
   ]
  },
  {
   "title": "Elastic search request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (elasticsearch_requests {namespace=\"$namespace\"}) by (operation)"
    }
   ]
  },
  {
   "title": "Num Shards",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "numshards_gauge {namespace=\"$namespace\"}"
    },
    {
     "expr": "rate(acquire_shards_count {namespace=\"$namespace\"}[5m])"
    },
    {
     "expr": "acquire_shards_count {namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Open workflows",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (elasticsearch_requests  {operation=\"RecordWorkflowExecutionStarted\",namespace=\"$namespace\" }) - sum (elasticsearch_requests  {operation=\"RecordWorkflowExecutionClosed\",namespace=\"$namespace\"}) ",
     "legendFormat": "Workflows on the fly"
    },
    {
     "expr": "elasticsearch_requests  {operation=\"RecordWorkflowExecutionClosed\", namespace=\"$namespace\"} ",
     "legendFormat": "{{ operation }}"
    },
    {
     "expr": "elasticsearch_requests  {operation=\"RecordWorkflowExecutionStarted\",namespace=\"$namespace\"} ",
     "legendFormat": "{{ operation }}"
    }
   ]
  },
  {
   "title": "Activities counters",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 76 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (activity_end_to_end_latency_count{domain = \"$domain\",namespace=\"$namespace\"}) by (workflowType ,activityType )",
     "legendFormat": "{{ activityType }}:{{ workflowType }}"
    }
   ]
  },
  {
   "title": "Activities counters",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 16, "x": 7, "y": 76 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (activity_end_to_end_latency_count{domain = \"$domain\",namespace=\"$namespace\"}) by (workflowType ,activityType )",
     "legendFormat": "{{ activityType }}:{{ workflowType }}"
    }
   ]
  },
  {
   "title": "Activities counters",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 84 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (activity_end_to_end_latency_count{domain = \"$domain\",namespace=\"$namespace\"}) by (workflowType ,activityType )",
     "legendFormat": "{{ activityType }}:{{ workflowType }}"
    }
   ]
  },
  {
   "title": "Activities counters",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 16, "x": 7, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (activity_end_to_end_latency_count{domain = \"$domain\",namespace=\"$namespace\"}) by (workflowType ,activityType )",
     "legendFormat": "{{ activityType }}:{{ workflowType }}"
    }
   ]
  }
 ]
}