{
 "title": "Cadence-Server-Basic",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cadence_requests,namespace)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(activity_end_to_end_latency_sum{namespace=\"$namespace\"}, domain)"
    }
   },
   { "name": "quantiles", "label": "Quantiles", "query": "0.5, 0.95, 0.99" }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Availability(server metrics)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cadence_errors{cadence_service=\"cadence_frontend\", namespace=\"$namespace\"})",
     "legendFormat": "\"Errors\""
    },
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\", namespace=\"$namespace\"})",
     "legendFormat": "\"Requests\""
    },
    {
     "expr": "1-(sum(cadence_errors{cadence_service=\"cadence_frontend\", namespace=\"$namespace\"}))/(sum(cadence_requests{cadence_service=\"cadence_frontend\", namespace=\"$namespace\"}))*100",
     "legendFormat": "\"Server availability\""
    }
   ]
  },
  {
   "title": "Activities Started Per Second",
   "type": "graph",
   "description": "TODO: how to add rate()? https://stackoverflow.com/questions/66286901/how-to-apply-rate-to-expression-with-name",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_requests{namespace=\"$namespace\",operation=\"PollForActivityTask\"}[2m]))",
     "legendFormat": "Activities Started per Second:"
    }
   ]
  },
  {
   "title": "StartWorkflow Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\",operation=\"StartWorkflowExecution\"}[1m]))",
     "legendFormat": "StartWorkflowExecution"
    },
    {
     "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\",operation=\"SignalWithStartWorkflowExecution\"}[1m]))",
     "legendFormat": "SignalWithStartWorkflowExecution:"
    }
   ]
  },
  {
   "title": "Decisions Started Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_requests{namespace=\"$namespace\",operation=\"PollForDecisionTask\"}[2m]))"
    }
   ]
  },
  {
   "title": "Periodical Test Suite Success(aka Canary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(workflow_success{cadence_service=\"cadence_history\",namespace=\"$namespace\",workflowType=\"workflow_sanity\"}) by (workflowType)",
     "legendFormat": "{{workflowType}}"
    }
   ]
  },
  { "title": "Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Service API success rate by Client(includes client side error like EntityNotExists)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Service Availability(server metrics)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1-sum(cadence_errors{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"})/sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}))*100"
    }
   ]
  },
  {
   "title": "All API per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "API per second(breakdown per operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m])) by (operation)"
    }
   ]
  },
  {
   "title": "Regular API Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\",operation!~\"CountWorkflowExecutions|GetWorkflowExecutionHistory|ListClosedWorkflowExecutions|ListOpenWorkflowExecutions|ListWorkflowExecutions|PollForActivityTask|PollForDecisionTask|QueryWorkflow\"}[2m]))))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "ListWorkflow API Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\",operation=~\"CountWorkflowExecutions|GetWorkflowExecutionHistory|ListClosedWorkflowExecutions|ListOpenWorkflowExecutions|ListWorkflowExecutions|PollForActivityTask|PollForDecisionTask|QueryWorkflow\"}[2m]))))",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Long Poll API Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\",operation=\"PollForDecisionTask\"}[2m]))))"
    },
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\",operation=\"PollForActivityTask\"}[2m]))))"
    }
   ]
  },
  {
   "title": "GetHistory/QueryWorkflow API Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\", cadence_service=\"cadence_frontend\", operation=~\"GetWorkflowExecutionHistory|QueryWorkflow\"}[2m]))))"
    }
   ]
  },
  {
   "title": "API  errors per second(breakdown per operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_errors{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "Internal server error"
    },
    {
     "expr": "sum(rate(cadence_errors_bad_request{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "Bad Requests error"
    },
    {
     "expr": "sum(rate(cadence_errors_query_failed{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "QueryFailed error"
    },
    {
     "expr": "sum(rate(cadence_errors_context_timeout{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "ContextTimeout error"
    },
    {
     "expr": "sum(rate(cadence_errors_entity_not_exists{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "EntityNotExists error"
    },
    {
     "expr": "sum(rate(cadence_errors_execution_already_started{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "WorkflowAlreadyStarted error"
    },
    {
     "expr": "sum(rate(cadence_errors_workflow_execution_already_completed{cadence_service=\"cadence_frontend\"}[2m]))",
     "legendFormat": "WorkflowAlreadyCompleted"
    }
   ]
  },
  {
   "title": "WorkflowClient API per seconds by domain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\", operation=~\"SignalWithStartworkflowExecution|SignalWorkflowExecution|StartWorkflowExecution|TerminateWorkflowExecution|ResetWorkflowExecution|RequestCancelWorkflowExecution|ListWorkflowExecutions\"}[2m])) by (domain, operation)",
     "legendFormat": "Domain: {{domain}}- Operation: {{operation}}"
    }
   ]
  },
  {
   "title": "Regular API Per Domain",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\", operation!~\"CountWorkflowExecutions|GetWorkflowExecutionHistory|ListClosedWorkflowExecutions|ListOpenWorkflowExecutions|ListWorkflowExecutions|PollForActivityTask|PollForDecisionTask|QueryWorkflow\"}) by (domain, operation)",
     "legendFormat": "Domain: {{domain}}- Operation: {{operation}}"
    },
    {}
   ]
  },
  {
   "title": "Top Domains for Regular Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 74 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\", operation=~\"SignalWithStartWorkflowExecution|SignalWorkflowxecution|StartWorkflowExecution|TerminateWorkflowExecution|ResetWorkflowExecution|RequestCancelWorkflowexecution|ListWorkflowExecutions\"}) by (domain)",
     "legendFormat": "{{domain}}"
    },
    {}
   ]
  },
  {
   "title": "Top Domains for Workflow Worker Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\", operation=~\"PollForDecisionTask|GetWorkflowExecutionHistory|RespondDecisionTaskCompleted\"}) by (domain)",
     "legendFormat": "{{domain}}{{operation}}"
    }
   ]
  },
  {
   "title": "Top Domains for Activity Worker Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 86 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\", operation=~\"PollForActivityTask|RespondActivityTaskCompleted\"}) by (domain)",
     "legendFormat": "{{domain}}{{operation}}"
    }
   ]
  },
  {
   "title": "Top Domains for All Requests",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 23, "x": 0, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cadence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}) by (domain)",
     "legendFormat": "{{domain}}{{operation}}"
    }
   ]
  },
  {
   "title": "History",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 },
   "collapsed": true,
   "panels": [
    {
     "title": "History Shard Movements",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(membership_changed_count{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=\"ShardController\"})",
       "legendFormat": "Membership Changed Count"
      },
      {
       "expr": "sum(shard_closed_count{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=\"ShardController\"})",
       "legendFormat": "Shard Closed Count"
      },
      {
       "expr": "sum(sharditem_created_count{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=\"ShardController\"})",
       "legendFormat": "Shard Item Created Count"
      },
      {
       "expr": "sum(sharditem_removed_count{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=\"ShardController\"})",
       "legendFormat": "Shard Item Removed Count"
      }
     ]
    },
    {
     "title": "History API per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m]))",
       "legendFormat": "Membership Changed Count"
      },
      {}
     ]
    },
    {
     "title": "History API Errors per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_errors{cadence_service=\"cadence_history\"}[2m]))",
       "legendFormat": "cadence errors: "
      },
      {
       "expr": "sum(rate(cadence_errors_entity_not_exists{cadence_service=\"cadence_history\"}[2m]))",
       "legendFormat": "Error: entity_not_exists"
      },
      {
       "expr": "sum(cadence_errors_execution_already_started{cadence_service=\"cadence_history\"})",
       "legendFormat": "Error: execution_already_started"
      },
      {
       "expr": "sum(cadence_errors_workflow_id_exceeded_warn_limit{cadence_service=\"cadence_history\"})",
       "legendFormat": "Error: workflow_id_exceeded_warn_limit"
      },
      {
       "expr": "sum(cadence_errors_workflow_execution_already_completed{cadence_service=\"cadence_history\"})",
       "legendFormat": "Error: workflow_execution_already_completed"
      }
     ]
    },
    {
     "title": "Regular API Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_bucket{namespace=\"$namespace\", cadence_service=\"cadence_history\",operation!~\"PollMutableState\"}[2m]))))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Transfer Tasks Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=~\"TransferActiveTask.*\"}[2m]))"
      }
     ]
    },
    {
     "title": "Timer Tasks Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(task_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=~\"TimerActiveTask.*\"}[2m]))"
      }
     ]
    },
    {
     "title": "Transfer Tasks Per Domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(task_requests_per_domain{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=~\"TransferActive.*\"}) by (domain)"
      }
     ]
    },
    {
     "title": "Timer Tasks Per Domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(task_requests_per_domain{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=~\"TimerActive.*\"}) by (domain)"
      }
     ]
    },
    {
     "title": "Transfer Task Latency Per Domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(task_latency_per_domain_bucket{namespace=\"$namespace\",operation=~\"TransferActive.*\"}[2m])) by (le, domain))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Timer Task Latency Per Domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(task_latency_per_domain_bucket{namespace=\"$namespace\",operation=~\"TimerActive.*\"}[2m])) by (le, domain))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Transfer Task Executing Latency By TaskType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(task_latency_per_domain_bucket{namespace=\"$namespace\",operation=~\"Transfer.*\"}[2m])) by (le, operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Timer Task Executing Latency By TaskType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(task_latency_per_domain_bucket{namespace=\"$namespace\",operation=~\"Timer.*\"}[2m])) by (le, operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Transfer Task Queue Latency By TaskType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(task_latency_queue_bucket{namespace=\"$namespace\",operation=~\"Transfer.*\"}[2m])) by (le, operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Timer Task Queue Latency By TaskType",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(rate(task_latency_queue_bucket{namespace=\"$namespace\",operation=~\"Timer.*\"}[2m])) by (le, operation))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Transfer/Timer task throttling by domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(transfer_task_throttled_counter{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=~\"Transfer.*\"}) by (domain)"
      },
      {
       "expr": "sum(timer_task_throttled_counter{cadence_service=\"cadence_history\",namespace=\"$namespace\",operation=~\"Transfer.*\"}) by (domain)"
      }
     ]
    },
    {
     "title": "Max History Size(in bytes) by domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(history_size_bucket{namespace=\"$namespace\",domain!=\"all\"}) by (le, domain)) * 1000000000"
      }
     ]
    },
    {
     "title": "Avg History Length by Domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " sum(rate(history_count_sum{namespace=\"$namespace\",domain!=\"all\"}[2m])) by (le, domain) * 1000000000 / sum(rate(history_count_count{namespace=\"$namespace\",domain!=\"all\"}[2m])) by (le, domain)"
      }
     ]
    },
    {
     "title": "Max Event Blob Size by Domain",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, sum(event_blob_size_bucket{namespace=\"$namespace\"}) by (le, domain)) * 1000000000"
      }
     ]
    }
   ]
  },
  {
   "title": "Matching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 },
   "collapsed": true,
   "panels": [
    {
     "title": "Matching APIs per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_requests{cadence_service=\"cadence_matching\",namespace=\"$namespace\"}[2m]))"
      },
      {}
     ]
    },
    {
     "title": "Matching API Errors per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_errors_per_tl{cadence_service=\"cadence_matching\"}[2m]))",
       "legendFormat": "Error: errors_per_tl"
      },
      {
       "expr": "sum(rate(cadence_errors_query_failed_per_tl{cadence_service=\"cadence_matching\"}[2m]))",
       "legendFormat": "Error: query_failed_per_tl"
      }
     ]
    },
    {
     "title": "Matching Regular API Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, (sum by (le, operation) (rate(cadence_latency_per_tl_bucket{namespace=\"$namespace\", cadence_service=\"cadence_matching\",operation!~\"QueryWorkflow\"}[2m]))))",
       "legendFormat": "{{operation}}"
      },
      {}
     ]
    },
    {
     "title": "Matching Long Poll API Latency ",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, (sum by (le, operation, tasklist) (rate(cadence_latency_per_tl_bucket{namespace=\"$namespace\", cadence_service=\"cadence_matching\",operation=~\"PollFor.*\"}[2m]))))",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Sync Match Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, (sum by (le, operation, tasklist, domain) (syncmatch_latency_per_tl_bucket{namespace=\"$namespace\", cadence_service=\"cadence_matching\"})))"
      }
     ]
    },
    {
     "title": "Async Match Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile($quantiles, (sum by (le, operation, tasklist, domain) (asyncmatch_latency_per_tl_bucket{namespace=\"$namespace\", cadence_service=\"cadence_matching\"})))"
      }
     ]
    },
    {
     "title": "AddTasks per Second - domain, tasklist breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_requests_per_tl{cadence_service=\"cadence_matching\",namespace=\"$namespace\", operation=~\"Add.*\"}[2m])) by (operation,tasklist,domain)"
      },
      {}
     ]
    },
    {
     "title": "Other API per Second - domain, tasklist breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_requests_per_tl{cadence_service=\"cadence_matching\",namespace=\"$namespace\",operation!~\"Add.*\"}[2m])) by (operation,tasklist,domain)"
      }
     ]
    }
   ]
  },
  { "title": "Persistence-Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Persistence-Database",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - ( sum(rate(persistence_errors{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m]))/\n  sum(rate(persistence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m])) ) ) * 100",
     "legendFormat": "cadence_frontend.persistence"
    },
    {
     "expr": "(1 - ( sum(rate(persistence_errors{cadence_service=\"cadence_matching\",namespace=\"$namespace\"}[2m]))/\n  sum(rate(persistence_requests{cadence_service=\"cadence_matching\",namespace=\"$namespace\"}[2m])) ) ) * 100",
     "legendFormat": "cadence_matching.persistence"
    },
    {
     "expr": "(1 - ( sum(rate(persistence_errors{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m]))/\n  sum(rate(persistence_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m])) ) ) * 100",
     "legendFormat": "cadence_history.persistence"
    },
    {
     "expr": "(1 - ( sum(rate(persistence_errors{cadence_service=\"cadence_worker\",namespace=\"$namespace\"}[2m]))/\n  sum(rate(persistence_requests{cadence_service=\"cadence_worker\",namespace=\"$namespace\"}[2m])) ) ) * 100",
     "legendFormat": "cadence_worker.persistence"
    }
   ]
  },
  {
   "title": "Persistence By Service TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m]))",
     "legendFormat": "cadence_frontend"
    },
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_matching\",namespace=\"$namespace\"}[2m]))",
     "legendFormat": "cadence_matching"
    },
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m]))",
     "legendFormat": "cadence_history"
    },
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_worker\",namespace=\"$namespace\"}[2m]))",
     "legendFormat": "cadence_worker"
    }
   ]
  },
  {
   "title": "Persistence By Operation TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m])) by (le, operation)",
     "legendFormat": "cadence_frontend-{{operation}}"
    },
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_matching\",namespace=\"$namespace\"}[2m])) by (le, operation)",
     "legendFormat": "cadence_matching-{{operation}}"
    },
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m])) by (le, operation)",
     "legendFormat": "cadence_history-{{operation}}"
    },
    {
     "expr": "sum(rate(persistence_requests{cadence_service=\"cadence_worker\",namespace=\"$namespace\"}[2m])) by (le, operation)",
     "legendFormat": "cadence_worker-{{operation}}"
    }
   ]
  },
  {
   "title": "Persistence By Operation Latency(in seconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (persistence_latency_bucket{namespace=\"$namespace\", cadence_service=\"cadence_frontend\"}))) ",
     "legendFormat": "cadence_frontend-{{operation}}"
    },
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (persistence_latency_bucket{namespace=\"$namespace\", cadence_service=\"cadence_matching\"}))) ",
     "legendFormat": "cadence_matching-{{operation}}"
    },
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (persistence_latency_bucket{namespace=\"$namespace\", cadence_service=\"cadence_history\"}))) ",
     "legendFormat": "cadence_history-{{operation}}"
    },
    {
     "expr": "histogram_quantile($quantiles, (sum by (le, operation) (persistence_latency_bucket{namespace=\"$namespace\", cadence_service=\"cadence_worker\"}))) ",
     "legendFormat": "cadence_worker-{{operation}}"
    }
   ]
  },
  {
   "title": "Persistence Error By Operation Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (le, operation) (persistence_errors{namespace=\"$namespace\", cadence_service=\"cadence_frontend\"})",
     "legendFormat": "cadence_frontend-{{operation}}"
    },
    {
     "expr": "sum by (le, operation) (persistence_errors{namespace=\"$namespace\", cadence_service=\"cadence_matching\"})",
     "legendFormat": "cadence_matching-{{operation}}"
    },
    {
     "expr": "sum by (le, operation) (persistence_errors{namespace=\"$namespace\", cadence_service=\"cadence_history\"})",
     "legendFormat": "cadence_history-{{operation}}"
    },
    {
     "expr": "sum by (le, operation) (persistence_errors{namespace=\"$namespace\", cadence_service=\"cadence_worker\"})",
     "legendFormat": "cadence_worker-{{operation}}"
    },
    {
     "expr": "sum by (le, operation) (persistence_errors_condition_failed{namespace=\"$namespace\", cadence_service=\"cadence_matching\"})",
     "legendFormat": "matching-condition-failed"
    },
    {
     "expr": "sum by (le, operation) (persistence_errors_shard_ownership_lost{namespace=\"$namespace\", cadence_service=\"cadence_history\"})",
     "legendFormat": "history-shard-owneship-lost"
    }
   ]
  },
  {
   "title": "Persistence-Kafka&ElasticSearch(Visibility)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 125 },
   "collapsed": true
  },
  {
   "title": "Persistence-Kafka&ElasticSearch(Visibility)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(1 - ( sum(rate(elasticsearch_errors{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m]))/\n  sum(rate(elasticsearch_requests{cadence_service=\"cadence_frontend\",namespace=\"$namespace\"}[2m])) ) ) * 100",
     "legendFormat": "cadence_frontend-{{operation}}"
    },
    {
     "expr": "(1 - ( sum(rate(elasticsearch_errors{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m]))/\n  sum(rate(elasticsearch_requests{cadence_service=\"cadence_history\",namespace=\"$namespace\"}[2m])) ) ) * 100",
     "legendFormat": "cadence_history-{{operation}}"
    }
   ]
  }
 ]
}