{
 "title": "Cadence-Client-Basic",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__=~ \"cadence_requests|cadence_decision_scheduled_to_start_latency_seconds_sum\"}, namespace)"
    }
   },
   {
    "name": "domain",
    "label": "Domain",
    "query": {
     "query": "label_values(activity_end_to_end_latency_sum{namespace=\"$namespace\"}, domain)"
    }
   },
   { "name": "quantiles", "label": "Quantiles", "query": "0.5, 0.95, 0.99" }
  ]
 },
 "panels": [
  {
   "title": "Workflow",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Workflow Start/Success",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_workflow_start_total{namespace=\"$namespace\",domain=\"$domain\"}[2m]))",
       "legendFormat": "Start"
      },
      {
       "expr": "sum(rate(cadence_workflow_completed_total{namespace=\"$namespace\",domain=\"$domain\"}[2m]))",
       "legendFormat": "Completed"
      },
      {
       "expr": "sum(rate(cadence_workflow_canceled_total{namespace=\"$namespace\",domain=\"$domain\"}[2m]))",
       "legendFormat": "Canceled"
      },
      {
       "expr": "sum(rate(cadence_workflow_continue_as_new_total_total{namespace=\"$namespace\",domain=\"$domain\"}[2m]))",
       "legendFormat": "Continued As New"
      },
      {
       "expr": "sum(rate(cadence_workflow_signal_with_start_total{namespace=\"$namespace\",domain=\"$domain\"}[2m]))",
       "legendFormat": "Signal With Start"
      }
     ]
    },
    {
     "title": "Workflow Failure",
     "type": "graph",
     "description": "TODO: how to add rate()? https://stackoverflow.com/questions/66286901/how-to-apply-rate-to-expression-with-name",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_workflow_failed{namespace=\"$namespace\"})) by (domain,workflowtype)",
       "legendFormat": "FailedOnClient"
      },
      {
       "expr": "sum(count(workflow_failed{cadence_service=\"cadence_history\",namespace=\"$namespace\"})) by (domain,workflowtype)",
       "legendFormat": "FailedOnServer"
      },
      {
       "expr": "sum(count(workflow_terminate{cadence_service=\"cadence_history\",namespace=\"$namespace\"})) by (domain,workflowtype)",
       "legendFormat": "Terminate"
      },
      {
       "expr": "sum(count(workflow_timeout{cadence_service=\"cadence_history\",namespace=\"$namespace\"})) by (domain,workflowtype)",
       "legendFormat": "Timeout"
      }
     ]
    },
    {
     "title": "Decision Poll Counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_decision_poll_total{namespace=\"$namespace\", Domain=\"$domain\"}))  by (domain,tasklist)",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(count(cadence_decision_poll_failed{namespace=\"$namespace\", Domain=\"$domain\"})) by (domain,tasklist)",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(count(cadence_decision_poll_no_task{namespace=\"$namespace\", Domain=\"$domain\"})) by (domain,tasklist)",
       "legendFormat": "No Task"
      },
      {
       "expr": "sum(count(cadence_decision_poll_succeed{namespace=\"$namespace\", Domain=\"$domain\"})) by (domain,tasklist)",
       "legendFormat": "Succeed"
      }
     ]
    },
    {
     "title": "Decisions Started Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_requests_per_tl{namespace=\"$namespace\",operation=\"AddDecisionTask\"}[2m])) by(tasklist,domain)"
      }
     ]
    },
    {
     "title": "Decision Scheduled To Start Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(cadence_decision_scheduled_to_start_latency_seconds_count[1m])) by (Domain, TaskList)*1000"
      },
      {
       "expr": "count(cadence_decision_scheduled_to_start_latency_seconds_max) by (Domain, TaskList) *1000"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cadence_decision_scheduled_to_start_latency_seconds_sum{Domain=\"$domain\",namespace=\"$namespace\"}  [5m])) by (le,Domain,TaskList) )"
      }
     ]
    },
    {
     "title": "NonDeterministicError and Worker Panic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_worker_panic{namespace=\"$namespace\"}[2m])) by(namespace,domain)"
      },
      {
       "expr": "sum(rate(cadence_non_deterministic_error{namespace=\"$namespace\"}[2m])) by(namespace,domain)"
      }
     ]
    },
    {
     "title": "Workflow Sticky Cache Hit Rate and Miss count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_sticky_cache_hit{namespace=\"$namespace\",domain=\"$domain\"})) by (Domain, TaskList)/\n(sum(count(cadence_sticky_cache_hit{namespace=\"$namespace\",domain=\"$domain\"})) by (Domain, TaskList)+\nsum(count(cadence_sticky_cache_miss{namespace=\"$namespace\",domain=\"$domain\"})) by (Domain, TaskList))*100"
      }
     ]
    },
    {
     "title": "Workflow Sticky Cache Eviction",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_sticky_cache_total_forced_eviction{namespace=\"$namespace\",domain=\"$domain\"})) by (domain)",
       "legendFormat": "RegularEviction"
      },
      {
       "expr": "sum(count(cadence_sticky_cache_thread_forced_eviction{namespace=\"$namespace\",domain=\"$domain\"})) by (domain)",
       "legendFormat": "ForcedEvictionCacheFull"
      }
     ]
    },
    {
     "title": "Workflow End to End Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(avg(cadence_workflow_endtoend_latency_bucket)) by (le,namespace,Domain,TaskList,workflowType))"
      },
      {
       "expr": "histogram_quantile(0.50, sum(avg(cadence_workflow_endtoend_latency_bucket)) by (le,namespace,Domain,TaskList,workflowType))"
      }
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Activity Task Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_activity_task_failed{namespace=\"$namespace\",domain=\"$domain\"})) by (activitytype)",
       "legendFormat": "Failed"
      },
      {
       "expr": "sum(count(cadence_activity_task_completed{namespace=\"$namespace\",domain=\"$domain\"})) by (activitytype)",
       "legendFormat": "Completed"
      },
      {
       "expr": "sum(rate(cadence_activity_task_timeouted{namespace=\"$namespace\",domain=\"$domain\"}[2m])) by (activitytype)",
       "legendFormat": "Timeouted"
      }
     ]
    },
    {
     "title": "Activity Execution Latency (ms)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(cadence_activity_execution_latency) by (namespace,domain,tasklist,activitytype)",
       "legendFormat": "avg latency"
      },
      {
       "expr": "max(cadence_activity_execution_latency) by (namespace,domain,tasklist,activitytype)"
      }
     ]
    },
    {
     "title": "Activity Poll Counters",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_activity_poll_total{namespace=\"$namespace\",domain=\"$domain\"})) by (activitytype)"
      },
      {
       "expr": "sum(count(cadence_activity_poll_failed{namespace=\"$namespace\",domain=\"$domain\"})) by (activitytype)",
       "legendFormat": "Completed"
      },
      {
       "expr": "sum(cadence_activity_poll_succeed{namespace=\"$namespace\",domain=\"$domain\"}) by (activitytype)"
      },
      {
       "expr": "sum(cadence_activity_poll_no_task{namespace=\"$namespace\",domain=\"$domain\"}) by (activitytype)"
      }
     ]
    },
    {
     "title": "ActivityTasks scheduled per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(cadence_requests_per_tl{cadence_service=\"cadence_matching\",namespace=\"$namespace\"}[5m])) by (domain,tasklist)"
      }
     ]
    },
    {
     "title": "Activity Scheduled To Start Latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(cadence_activity_scheduled_to_start_latency_count{Domain=\"$domain\",namespace=\"$namespace\"}) by (Domain, TaskList,ActivityType)"
      },
      {
       "expr": "max(cadence_activity_scheduled_to_start_latency_max{Domain=\"$domain\",namespace=\"$namespace\"}) by (Domain,TaskList,ActivityType)"
      },
      {
       "expr": "histogram_quantile(0.95, max(cadence_activity_scheduled_to_start_latency_sum{Domain=\"$domain\",namespace=\"$namespace\"} ) by (leDomain, TaskList,ActivityType) )"
      }
     ]
    },
    {
     "title": "Activity Failure",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(count(cadence_activity_execution_failed{namespace=\"$namespace\",domain=\"$domain\"}))by(domain,activitytype)\n",
       "legendFormat": "ExecFailedOnClient"
      },
      {
       "expr": "sum(count(cadence_activity_task_panic{namespace=\"$namespace\",domain=\"$domain\"}))by(domain)",
       "legendFormat": "TaskPanicOnClient"
      },
      {
       "expr": "sum(count(cadence_activity_task_failed{namespace=\"$namespace\",domain=\"$domain\"}))by(domain,activitytype)",
       "legendFormat": "TaskFailedOnClient"
      },
      {
       "expr": "sum(count(cadence_activity_task_canceled{namespace=\"$namespace\",domain=\"$domain\"}))by(domain)",
       "legendFormat": "TaskCanceledOnClient"
      },
      {
       "expr": "sum(count(heartbeat_timeout{cadence_service=\"cadence_history\",namespace=\"$namespace\",domain=\"$domain\"}))by(domain)",
       "legendFormat": "HeartbeatTimeout"
      },
      {
       "expr": "sum(count(schedule_to_start_timeout{cadence_service=\"cadence_history\",namespace=\"$namespace\",domain=\"$domain\"}))by(domain)",
       "legendFormat": "ScheduledToStartTimeout"
      },
      {
       "expr": "sum(count(start_to_close_timeout{cadence_service=\"cadence_history\",namespace=\"$namespace\",domain=\"$domain\"}))by(domain)",
       "legendFormat": "StartToCloseTimeout"
      },
      {
       "expr": "sum(count(schedule_to_close_timeout{cadence_service=\"cadence_history\",namespace=\"$namespace\",domain=\"$domain\"}))by(domain)",
       "legendFormat": "ScheduledToCloseTimeout"
      }
     ]
    }
   ]
  },
  {
   "title": "Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service API success rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(\n1 - count(cadence_error{namespace=\"$namespace\",domain=\"$domain\"})by(domain)/\ncount(cadence_request{namespace=\"$namespace\",domain=\"$domain\"})by(domain)\n) * 100\n\n\n",
       "legendFormat": "ExecFailedOnClient"
      }
     ]
    },
    {
     "title": "Service API Latency (TODO exclude long-poll APIs)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(cadence_latency{Domain=\"$domain\",namespace=\"$namespace\"} [1m])) by (Domain)"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(cadence_latency{Domain=\"$domain\",namespace=\"$namespace\"}  [5m])) by (le,domain) )"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(cadence_latency{Domain=\"$domain\",namespace=\"$namespace\"}  [5m])) by (le,domain) )"
      }
     ]
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Max History Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($quantiles, (max by (le, domain) (history_size_bucket{namespace=\"$namespace\"})))*1000000000"
    }
   ]
  },
  {
   "title": "Avg History Length ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (domain) (history_count_sum{namespace=\"$namespace\",domain!=\"all\"}/history_count_count{namespace=\"$namespace\",domain!=\"all\"})\n*1000000000"
    }
   ]
  },
  {
   "title": "Max Event Blob Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(histogram_quantile(1, max(event_blob_size_bucket) by (le)))*1000000000"
    }
   ]
  }
 ]
}